cros_bundle_firmware: Correct missing binascii import
This import is missing and without this the code will not work.

BUG=chromium:220915
TEST=manual
Build image with an embedded 'fdtmap' section. See that it now succeeds
instead of giving an error:

NameError: global name 'binascii' is not defined

Change-Id: I0dbe38b119108d33e557b454bfc71d22556fd48f
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/49401